# Generated by Django 3.0.5 on 2020-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_duration',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='IMG_20200503_094546.jpg', upload_to='profile/images/'),
        ),
    ]
