# Generated by Django 3.0.5 on 2020-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200809_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='read_duration',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
