# Generated by Django 3.0.5 on 2020-08-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200811_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_views',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
