# Generated by Django 3.0.5 on 2020-08-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200811_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
