# Generated by Django 3.0.5 on 2020-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200817_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
