# Generated by Django 3.0.5 on 2020-08-17 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_post_number_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='co_author',
            field=models.ManyToManyField(related_name='copublisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
