# Generated by Django 3.0.5 on 2020-08-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_collaburation_author_post_liked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaburation_author',
            new_name='Collaburating_author',
        ),
    ]
