# Generated by Django 3.0.5 on 2020-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200818_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='author_request',
            name='message',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
