# Generated by Django 3.0.5 on 2020-08-19 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_auto_20200819_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requst_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
