# Generated by Django 3.0.5 on 2020-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_author_request_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='author_request',
            name='message',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='author_request',
            name='options',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='author_request',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
