# Generated by Django 3.0.5 on 2020-08-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_auto_20200819_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_request',
            name='category',
        ),
        migrations.RemoveField(
            model_name='author_request',
            name='options',
        ),
        migrations.CreateModel(
            name='Author_request_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requst_cat_approval', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requst_cat_publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
