# Generated by Django 3.0.5 on 2020-08-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200819_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='markas_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
