# Generated by Django 3.0.5 on 2020-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200820_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
