# Generated by Django 3.0.5 on 2020-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200823_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request_category',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
