# Generated by Django 3.0.5 on 2020-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200823_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
