# Generated by Django 3.0.5 on 2020-08-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200823_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approved',
            new_name='approved_by',
        ),
    ]
