# Generated by Django 3.0.5 on 2020-08-25 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0038_auto_20200824_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaburating_author',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaburation_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaburating_author',
            name='approved_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collaburating_author',
            name='author_in_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaburation_requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaburating_author',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
