# Generated by Django 3.0.5 on 2020-08-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200825_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaburating_author',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collaburating_author',
            name='approved_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collaburating_author',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
