# Generated by Django 3.0.5 on 2020-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_tag',
            field=models.ManyToManyField(related_name='tag', to='blog.Tags'),
        ),
    ]
