# Generated by Django 3.0.5 on 2020-08-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0043_auto_20200826_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='co_author',
        ),
        migrations.AddField(
            model_name='collaburating_author',
            name='requested_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaburation_requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaburating_author',
            name='author_in_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaburatee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaburating_author',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
