# Generated by Django 3.0.5 on 2020-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20200826_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaburating_author',
            name='requested_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
