# Generated by Django 3.0.5 on 2020-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_collaburating_author_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaburating_author',
            name='request_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
