# Generated by Django 3.0.5 on 2020-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_collaburating_author_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_request_category',
            name='options',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
