# Generated by Django 3.0.5 on 2020-08-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20200827_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_request_category',
            name='modified_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='author_request_category',
            name='options',
            field=models.CharField(default='Request Category', max_length=20, null=True),
        ),
    ]
