# Generated by Django 3.0.5 on 2020-08-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0048_auto_20200827_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='message_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author_request',
            name='weight',
            field=models.CharField(default='Heavy', max_length=10),
        ),
    ]
