# Generated by Django 3.0.5 on 2020-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20200901_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
