# Generated by Django 3.0.5 on 2020-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_post_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_history',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
