# Generated by Django 3.0.5 on 2020-09-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_post_history_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='neighbours_voice',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
