# Generated by Django 3.0.5 on 2020-09-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_comment_neighbours_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='neighbours_voice',
            new_name='active_writer',
        ),
    ]
