# Generated by Django 3.0.5 on 2020-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_newsletter_subcribers_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
