# Generated by Django 3.0.5 on 2020-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20200928_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_request',
            name='encodededpk',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
